### ISSUE TITLE
本来想下载下来试一试的，没装vs，也没法自己编译

### ISSUE THREAD

**Issue by code2u** [movsb/common#1]
本来想下载下来试一试的，没装vs，也没法自己编译

**Comment by code2u** [comment]
那你自己的代码，在自己电脑上没有编译过吗？还是说虽然本地编译了，但是没有发布到github上面？

**Comment by code2u** [comment]
@movsb 是不是也需要@下你才能邮件通知你？

**Comment by movsb** [comment]
@code2u 在自己电脑上编译那倒是常有的事, 不过一般是传到网盘上, 然后在博客/项目主页上提供下载链接, 因为github主要是作代码版本控制的, 放太大的bin在上面也不太好.
我要该项目的主要维护者, 默认是订阅了评论通知的(右边有个Subscribe notifications), 所以无论是谁的评论, 应该都会收到通知, 但如果非项目的参与者, 应该是要@才能收到通知, 我想是这样.

**Comment by code2u** [comment]
@movsb 看来似乎要搞个网盘什么的，专门放编译完成的文件才行。好像其他项目确实没看到有直接将文件发到github的。

**Comment by code2u** [comment]
@movsb 想问下，你做的这个串口调试程序，有用到什么控件吗？还是直接使用window自己的api什么的？另外，你的UI程序，是直接使用windows的API开发的吗？还是有用到mfc之类的东西？

**Comment by movsb** [comment]
@code2u 全部是系统的控件+纯api写的, 没有使用任何mfc的东西.

**Comment by code2u** [comment]
@movsb  这样啊，那也好。不过，现在写界面，似乎一般使用WPF或者C#之类的东西比较多。

**Comment by movsb** [comment]
@code2u 主要是不会C#, 目前没精力去学, 把喜欢的学好了再说.
