### ISSUE TITLE
关闭串口后，combobox会重置为选中COM1（如果有的话）

### ISSUE THREAD

**Issue by cmheia** [movsb/common#3]
所以经常开开关关串口的时候容易出乱子。
另外希望接收窗口的右键菜单增加清空接收区和开关串口选项，这两个是最常用的操作。

**Comment by movsb** [comment]
囧，刚才试了一下，果然会选中到第一个了。
但之前确实不是这样的，不知道什么时候改出问题了，这周末的时候看看。
清空接收区在右键菜单里面是有的哦。

**Comment by movsb** [comment]
你那儿有编译器吗，我修复了。

**Comment by movsb** [comment]
@cmheia 你那儿有编译器吗，我修复了。你试下。

**Comment by cmheia** [comment]
测试OK，问题解决。
这大半夜的
→_→
