### ISSUE TITLE
DTR/RTS引脚电平控制？

### ISSUE THREAD

**Issue by cmheia** [movsb/common#4]
正在使用的某串口设备，需要DTR，否则收不到数据。

**Comment by movsb** [comment]
@cmheia 
https://github.com/movsb/common/commit/128eb5d#diff-c7d7964a180cc9309ec29cafe3d39d62L1
这个之前也是有的，后来不知道为什么就给去掉了。

**Comment by cmheia** [comment]
所以大概可以把这些代码贴回去取得功能，明天试试。

**Comment by movsb** [comment]
@cmheia 加上了，可以试试。

**Comment by cmheia** [comment]
刚才试了下，可以DTR了，但是有点小问题：第一次点击“设定”后，该按钮即被禁用，关闭串口后仍然是禁用状态，需要展开一次左侧的ComboBox才能解锁。
大概需要在关闭或打开串口的事件里加上重新启用“设定”按钮的操作。
如果能记住DTR/RTS的设置状态，关闭再重新打开上一次的串口后，就应用上一次的设定，会比较方便。

**Comment by movsb** [comment]
@cmheia 嗯，没考虑到在关闭后重新启用那个按钮的情况，我干脆直接去掉禁用那个状态得了，意义不大。
至于设定状态的话，设备驱动是会自动保存DTR/RTS状态的，我试过的几款串口设备都支持。如果不支持的话，状态就比较难持久化了，毕竟串口号随时都可能改变。
